twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        trackingConfig: '@App\Service\Tracking\MatomoConfig'

when@test:
    twig:
        strict_variables: true
